name: flutter_test_plugin
description: A basic Flutter package for testing GitHub Actions workflow.
version: 0.0.1
author: Subhash Chandra <subhashchandra30720@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_test_plugin
        pluginClass: FlutterTestPlugin
      ios:
        pluginClass: FlutterTestPlugin

# Optional: Add more dependencies here if needed.
