name: Flutter Package Dry Run

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Runs dry-run on PR creation, update, or reopening
  push:
    branches:
      - '**'  # Runs dry-run on any push to any branch

jobs:
  dry-run:
    runs-on: ubuntu-latest
    name: Flutter Pub Publish --dry-run
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run flutter pub publish --dry-run
        run: flutter pub publish --dry-run
