name: Publish Flutter Package

on:
  push:
    branches:
      - main  # Only run this workflow on pushes to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Package to Pub.dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Set up Credentials
        # run: echo "${{ secrets.PUB_DEV_TOKEN }}" > ~/.pub-cache/credentials.json

      # - name: Publish to pub.dev
      #   run: flutter pub publish --force
      #   env:
      #     PUB_ENVIRONMENT: github-action
