name: Publish Flutter Package

on:
  push:
    branches:
      - '**'  # Runs dry-run on any push to any branch

jobs:
  dry-run:
    runs-on: ubuntu-latest
    name: Flutter Pub Publish --dry-run
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: dart pub get

      - name: Run flutter pub publish --dry-run
        run: flutter pub publish --dry-run

  publish:
    needs: dry-run  # This ensures publish runs only if dry-run succeeds
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only run on the main branch
    runs-on: ubuntu-latest
    name: Publish Package to Pub.dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      # - name: Set up Credentials
      #   run: echo "${{ secrets.PUB_DEV_TOKEN }}" > ~/.pub-cache/credentials.json

      # - name: Publish to pub.dev
      #   run: flutter pub publish --force
      #   env:
      #     PUB_ENVIRONMENT: github-action
